name: Mi primer CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Dar permisos de ejecución al Wrapper de Maven
        run: chmod +x mvnw

      - name: Compilar el proyecto
        run: ./mvnw compile --no-transfer-progress

      - name: Ejecutar pruebas (Unitarias e Integración)
        run: ./mvnw verify --no-transfer-progress

      - name: Generar informe de resultados de tests en GitHub (Dorny)
        uses: dorny/test-reporter@v1
        if: always() # Se ejecuta aunque fallen algunos tests
        with:
          name: Resultados de Pruebas
          path: target/surefire-reports/*.xml, target/failsafe-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Generar Badge de Cobertura con Jacoco
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: .github/badges
          generate-branches-badge: true

      - name: Hacer Commit de los Badges Generados
        if: github.event_name == 'push'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/badges/
          git commit -m "Autogenerar badges de cobertura [skip ci]" || echo "No hay cambios para commitear"
          git push